package it.cnr.ilc.lexo.service.data.attestation.output;

import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import it.cnr.ilc.lexo.service.data.Data;
import java.util.ArrayList;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;

/** Result of an atomic attestation deletion batch. */
@ApiModel(description = "Result of an atomic attestation deletion batch")
public class AttestationDeletionResult implements Data {

    @ApiModelProperty(value = "id selecting the per-text attestation graph")
    public String fileId;
    @ApiModelProperty(value = "number of deleted attestations")
    public int deletedCount;
    @ApiModelProperty(value = "deleted attestations")
    public List<AttestationDeletionItem> deleted =
            new ArrayList<AttestationDeletionItem>();
    @ApiModelProperty(value = "orphan NIF loci generated by the attestation service and deleted from LexOTexts")
    public List<String> deletedLoci = new ArrayList<String>();
    @ApiModelProperty(value = "loci retained because they are still attested or were not generated by the attestation service")
    public List<String> retainedLoci = new ArrayList<String>();
    @ApiModelProperty(value = "remaining per-text frequencies keyed by observable IRI; zero means that the frequency object was removed")
    public Map<String, Integer> frequencies =
            new LinkedHashMap<String, Integer>();

    public AttestationDeletionResult() {
    }
}
